### ISSUE TITLE
add new anna picture to the site

### ISSUE THREAD

**Issue by sodevious** [sawhorse/sawhorse.github.io#11]
![anna1](https://cloud.githubusercontent.com/assets/915966/11881196/2a7bde3a-a4d3-11e5-8a19-a13f734b9ae0.jpg)
![anna](https://cloud.githubusercontent.com/assets/915966/11881197/2a7d7f10-a4d3-11e5-99fc-72bec1fb1f2d.jpg)

**Comment by lvannostrand** [comment]
https://github.com/sawhorse/sawhorse.github.io/commit/0267650f343dd8fa50d442202a2c759b8f2261f5
