### ISSUE TITLE
add new rocco picture to the site

### ISSUE THREAD

**Issue by sodevious** [sawhorse/sawhorse.github.io#12]
![rocco](https://cloud.githubusercontent.com/assets/915966/11881188/204f4fe6-a4d3-11e5-99fd-ffa31c2f8c2f.jpg)
![rocco1](https://cloud.githubusercontent.com/assets/915966/11881189/204ffa22-a4d3-11e5-9971-fab7604e1803.jpg)

**Comment by lvannostrand** [comment]
https://github.com/sawhorse/sawhorse.github.io/commit/0267650f343dd8fa50d442202a2c759b8f2261f5
