### ISSUE TITLE
add new andrew picture

### ISSUE THREAD

**Issue by sodevious** [sawhorse/sawhorse.github.io#13]
![andrew](https://cloud.githubusercontent.com/assets/915966/11881262/92eea4ac-a4d3-11e5-9c6f-d131ec3eaba3.jpg)
![andrew2](https://cloud.githubusercontent.com/assets/915966/11881263/92f96720-a4d3-11e5-992b-f09c1cd331ac.jpg)

**Comment by lvannostrand** [comment]
https://github.com/sawhorse/sawhorse.github.io/commit/0267650f343dd8fa50d442202a2c759b8f2261f5
